ga4gh/beacon_v2_default_model:
  model_enabled: True
  entry_types:
    analysis:
      entry_type_enabled: True
      granularity: record
      endpoint_name: analyses
      open_api_endpoints_definition: https://raw.githubusercontent.com/ga4gh-beacon/beacon-v2/main/models/json/beacon-v2-default-model/analyses/endpoints.json
      function: get_phenotypic_endpoint
      allow_queries_without_filters: True
      allow_id_query: True #Â analyses/{id}
      connection:
        name: mongo
        database: beacon
        table: analyses
      info:
        name: Bioinformatics analysis
        ontology_id: edam:operation_2945
        ontology_name: Analysis
        description: Apply analytical methods to existing data of a specific type.
      schema:
        specification: Beacon v2
        defaultSchema_id: beacon-analysis-v2.0.0
        defaultSchema_name: Default schema for a bioinformatics analysis
        defaultSchema_reference_to_schema_definition: https://raw.githubusercontent.com/ga4gh-beacon/beacon-v2/main/models/json/beacon-v2-default-model/analyses/defaultSchema.json'
        defaultSchema_schema_version: v2.0.0
        aditionally_supported_schemas:
          - beacon-analysis-v2.0.1
          - beacon-analysis-v2.1.0
          - beacon-analysis-v2.1.1
          - beacon-analysis-v2.1.2
          - beacon-analysis-v2.2.0
      lookups:
        biosample: # afegir la URL
          enable: True
          function: get_phenotypic_cross_query
        cohort:
          enable: True
          function: get_phenotypic_endpoint_of_cohort
        dataset:
          enable: True
          function: get_phenotypic_endpoint_of_dataset
        genomicVariant:
          enable: True
          function: get_phenotypic_endpoint_of_variants
        individual:
          enable: True
          function: get_phenotypic_cross_query
        run:
          enable: True
          function: get_phenotypic_cross_query

EUCAIM:
  enable: True
  routes:
  versions_supported:
    - v0.0.1
      



# Agafar com a identificador d'usuari el que digui la OIDC spec.